# ==============================================================================
# Docker Compose - Development Override
# Use: docker compose -f docker-compose.yml -f docker-compose.dev.yml up
# ==============================================================================

services:
  # Auth Service - Development Mode
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_LEVEL: debug
    volumes:
      - ./services/auth-service:/var/www:cached
    command: >
      sh -c "composer install &&
             php artisan key:generate --force &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

