global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'microservices-dev'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (host metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'auth-service'
      - target_label: service
        replacement: 'auth-service'

  # Inventory Service
  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory-service:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'inventory-service'
      - target_label: service
        replacement: 'inventory-service'

  # Sales Service
  - job_name: 'sales-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sales-service:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'sales-service'
      - target_label: service
        replacement: 'sales-service'

  # Financial Service
  - job_name: 'financial-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['financial-service:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'financial-service'
      - target_label: service
        replacement: 'financial-service'

  # PostgreSQL Exporter - Auth DB
  - job_name: 'postgres-auth'
    static_configs:
      - targets: ['postgres-exporter-auth:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'auth-db'

  # PostgreSQL Exporter - Inventory DB
  - job_name: 'postgres-inventory'
    static_configs:
      - targets: ['postgres-exporter-inventory:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'inventory-db'

  # PostgreSQL Exporter - Sales DB
  - job_name: 'postgres-sales'
    static_configs:
      - targets: ['postgres-exporter-sales:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'sales-db'

  # PostgreSQL Exporter - Financial DB
  - job_name: 'postgres-financial'
    static_configs:
      - targets: ['postgres-exporter-financial:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'financial-db'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

